[project]
name = "q_simulator"
version = "0.1.0"
description = "BP Uni Stuttgart - Simulation von Quantenschaltungen"
readme = "README.md"
authors = [
    { name = "jona-sh" },
    { name = "felglo" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "qiskit>=2.5.2",
    "qiskit-aer>=0.17.2",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
extend-select = ["NPY"]

[tool.mypy]
disable_error_code = ["import-untyped"]
